# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('titleID', models.CharField(max_length=255, unique=True)),
                ('especialidade', models.CharField(choices=[('HD', 'HIDRAULICA'), ('EL', 'ELETRICA'), ('MC', 'MACENARIA'), ('OU', 'OUTROS')], default='-', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.IntegerField(default=0)),
                ('description_full', models.TextField(verbose_name='Descrição completa')),
                ('description_brief', models.TextField(max_length=140, verbose_name='Descrição breve')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
