# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoDeManutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodemanutencao',
            name='titleID',
            field=models.CharField(max_length=255),
        ),
    ]
