# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='number',
        ),
    ]
