# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0002_auto_20171006_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='planosDeMan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planoDeManutencao.PlanoDeManutencao'),
        ),
    ]
